SLEAdminPortal/Controllers/DeviceEnvironmentMappingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using log4net;
using SLEAdminPortal.Models;

namespace SLEAdminPortal.Controllers
{
    [Authorize]
    [SLEAdminPortal.FilterConfig.SessionExpire]
    public class DeviceEnvironmentMappingController :Controller
    {
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        public ActionResult Index()
        {
            try
            {
                if (TempData["ErrMsg"] != null)
                {
                    string msg = TempData["ErrMsg"].ToString().Replace('\'', ' ').Replace('\n', ' ').Replace('\r', ' ');

                    if (msg.Contains("Violation of PRIMARY KEY"))
                        msg = "Already Exists";

                    ViewBag.msg = msg;
                    TempData["ErrMsg"] = null;
                }
                //Get All Device Environment Mapping
                List<DeviceEnvironmentMappingModel> lst = new List<DeviceEnvironmentMappingModel>();
                lst = new Managers.DeviceEnvironmentMappingManager().GetDeviceEnvironmentList();
                return View(lst);
            }
            catch (Exception e)
            {
                ViewBag.msg = e.Message.ToString();
                return View();
            }
        }

        //Show Popup For Create
        public ActionResult Create()
        {
            try
            {
                DeviceEnvironmentMappingModel model = new DeviceEnvironmentMappingModel();

                //Load All Drop Down List
                var deviceLst = new Managers.DeviceEnvironmentMappingManager().GetDeviceDdl();
                ViewData["Device"] = new SelectList(deviceLst.OrderBy(x => x.Device_Id), "Device_Id", "FQDN");

                var envList = new Managers.DeviceEnvironmentMappingManager().GetEnvDdl();
                ViewData["Environment"] = new SelectList(envList.OrderBy(x => x.EnvName), "EnvironmentMasterId", "EnvName");

                return PartialView("_DevEnvMap", model);
            }
            catch (Exception e)
            {
                TempData["ErrMsg"] = e.Message.ToString();
                return RedirectToAction("Index");
            }
        }

        //Save Device Environment Mapping
        public ActionResult Save(DeviceEnvironmentMappingModel model)
        {
            try
            {
                bool result = new Managers.DeviceEnvironmentMappingManager().SaveDeviceEnvironmentMapping(model);
                TempData["ErrMsg"] = "Record Saved";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["ErrMsg"] = e.Message.ToString();
                return RedirectToAction("Index");
            }
        }

        // Show Popup For Edit
        public ActionResult Edit(string deviceid, decimal environmentid)
        {
            try
            {
                //Load All Drop Down List
                var deviceLst = new Managers.DeviceEnvironmentMappingManager().GetDeviceDdl();
                ViewData["Device"] = new SelectList(deviceLst.OrderBy(x => x.FQDN), "Device_Id", "FQDN");

                var envList = new Managers.DeviceEnvironmentMappingManager().GetEnvDdl();
                ViewData["Environment"] = new SelectList(envList.OrderBy(x => x.EnvName), "EnvironmentMasterId", "EnvName");

                // Load Single Record
                DeviceEnvironmentMappingModel lst = new DeviceEnvironmentMappingModel();
                lst = new Managers.DeviceEnvironmentMappingManager().GetByDeviceEnvironmentId(deviceid, environmentid);

                lst.EditDeviceId = deviceid;
                lst.EditEnvironmentMasterId = environmentid;

                return PartialView("_DevEnvMap", lst);
            }
            catch (Exception e)
            {
                TempData["ErrMsg"] = e.Message.ToString();
                return RedirectToAction("Index");
            }
        }

        //Update Device Environment Mapping
        public ActionResult Update(DeviceEnvironmentMappingModel model)
        {
            try
            {
                bool result = new Managers.DeviceEnvironmentMappingManager().EditDeviceEnvironmentMapping(model);
                TempData["ErrMsg"] = "Record Updated";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["ErrMsg"] = e.Message.ToString();
                return RedirectToAction("Index");
            }
        }

        //Delete Device Environment Mapping
        public ActionResult Delete(string deviceid, decimal environmentid)
        {
            try
            {
                bool result = new Managers.DeviceEnvironmentMappingManager().DeleteDeviceEnvironmentMapping(environmentid, deviceid);
                return Json(new { msg = "Record Deleted", result = true });
            }
            catch (Exception e)
            {
                return Json(new { msg = e.Message, result = true });
            }
        }

    }
}

SLEAdminPortal/Views/DeviceEnvironmentMapping/Index.cshtml
@{
    ViewBag.Title = "Device Environment Mapping";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<SLEAdminPortal.Models.DeviceEnvironmentMappingModel>

<div class="wrapper wrapper-content animated fadeInRight">
    <div id="tabwhite" class="row">
        <div class="col-lg-12">
            <div class="tabs-container">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#tab-1">Device Environment Mapping List</a></li>
                </ul>

                <div class="tab-content">
                    <div id="tab-1" class="tab-pane active">
                        <div class="panel-body">
                            <form role="form">
                                <div class="form-group col-lg-12"> <a class="btn btn-primary" onclick="createModal()">Add New Device Environment Mapping</a> </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Total Device Environment Mapping : @Model.Count() </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">Config option 1</a>
                            </li>
                            <li>
                                <a href="#">Config option 2</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="ibox-content">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Device Id</th>
                                <th>Environment Name</th>                                
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 1; i <= @Model.Count(); i++)
                            {
                                <tr>
                                    <td>@i</td>
                                    <td>@Model.ElementAt(i - 1).DeviceId</td>
                                    <td>@Model.ElementAt(i - 1).EnvName</td>
                                    <td><button type="button" class="btn btn-primary" onclick="editModal(@Model.ElementAt(i - 1).EnvironmentMasterId, '@Model.ElementAt(i - 1).DeviceId');">Edit</button></td>
                                    <td><div class="form-group col-lg-12"> <a class="btn btn-danger" onclick="DeleteRecord(@Model.ElementAt(i - 1).EnvironmentMasterId, '@Model.ElementAt(i - 1).DeviceId');">Delete</a> </div></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@* Modal For Create *@
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Add New Device Environment Mapping</h4>
            </div>
            @using (Html.BeginForm("Save", "DeviceEnvironmentMapping", FormMethod.Post))
            {
                <div class="modal-body">
                    <div id="createModal">

                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            }
        </div>
    </div>
</div>

@* Modal For Edit *@
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Edit Device Environment Mapping</h4>
            </div>
            @using (Html.BeginForm("Update", "DeviceEnvironmentMapping", FormMethod.Post))
            {
                <div class="modal-body">
                    <div id="editModal">

                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            }
        </div>
    </div>
</div>

<script type="text/javascript">

    $(function () {
        var msg= "@ViewBag.msg";
        if (msg != null && msg != "")
            alert(msg);
    });

    //Create Device Environment Mapping
    function createModal() {
        $.ajax({
            url: '@Url.Action("Create", "DeviceEnvironmentMapping")',
            contenttype: 'application/html; charset=utf-8',
            type: 'GET',
            dataType: 'html'
        })
        .success(function (result) {
            $("#createModal").html(result);
            $('form').removeData('validator');
            $('form').removeData('unobtrusiveValidation');
            $.validator.unobtrusive.parse('form');
            $("#myModal").modal('show');
        });
    }

    //Edit Device Environment Mapping
    function editModal(id1,id2) {
        $.ajax({
            url: '../DeviceEnvironmentMapping/Edit/?deviceid=' + id2 + '&environmentid='+id1,
            contentType: 'application/json; charset=utf-8',
            type: 'GET',
            datatype: 'html',
            cache: false,
            success: function (result) {
                $("#editModal").html(result);
                $('form').removeData('validator');
                $('form').removeData('unobtrusiveValidation');
                $.validator.unobtrusive.parse('form');
                $("#myModal1").modal('show');
            },
            error: function (result) {
            }
        });
    }

    //Delete Device Environment Mapping
    function DeleteRecord(id1,id2) {
        if (confirm("Are you sure you want to delete this row?")) {
            var EnvironmentMasterId;

            $.ajax({
                url: '../DeviceEnvironmentMapping/Delete/?deviceid=' + id2 + '&environmentid='+id1,
                contentType: 'application/json; charset=utf-8',
                type: 'POST',
                cache: false,
                success: function (data) {
                    if(data.result==true){
                        alert("Record Deleted");
                        window.location.reload();
                    }
                    else
                        alert(data.msg);
                },
                error: function (result) {
                }
            });
        }
    }

</script>

SLEAdminPortal/Views/DeviceEnvironmentMapping/_DevEnvMap.cshtml
@model SLEAdminPortal.Models.DeviceEnvironmentMappingModel

<div class="form-group">
    <label>Device</label>
    @Html.DropDownListFor(m => m.DeviceId, (SelectList)ViewData["Device"], "-Select Device-", new { @required = "required", @class = "form-control" })
    @Html.ValidationMessageFor(model => model.DeviceId, "Select Device", new { @class = "text-danger" })
</div>

<div class="form-group">
    <label>Environment</label>
    @Html.HiddenFor(m => m.EditDeviceId)
    @Html.HiddenFor(m => m.EditEnvironmentMasterId)
    
    @Html.DropDownListFor(m => m.EnvironmentMasterId, (SelectList)ViewData["Environment"], "-Select Environment-", new { @required = "required", @class = "form-control" })
    @Html.ValidationMessageFor(m => m.EnvironmentMasterId, "Select Environment", new { @class = "text-danger" })
</div>