SLEAdminPortal/Controllers/AdminMasterController.cs
//************************************************************************************************
// Comment: Security Process Controller - Role Master, Securable Features, Role Features
// Created: Mar 20, 2016
// Author: TechUnison India (Velmani Karnan)
//*************************************************************************************************

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SLEAdminPortal.Models;
using System.Data;
using SLEAdminPortal.Managers;

namespace SLEAdminPortal.Controllers
{
    [Authorize]
    [SLEAdminPortal.FilterConfig.SessionExpire]
    public class AdminMasterController : Controller
    {
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        public ActionResult RoleMaster(string RoleID, string RoleNames, string RoleDescription)
        {
            try
            {
                AdminRoleModel models = new AdminRoleModel();
                if (!string.IsNullOrEmpty(RoleID) || !string.IsNullOrEmpty(RoleNames) || !string.IsNullOrEmpty(RoleDescription))
                {
                    models.AdminRoles = new Managers.AdminManager().GetSpecificRoleList(RoleID, RoleNames, RoleDescription);
                    return View("RoleMaster", models);
                }
                else
                {
                    models.AdminRoles = new Managers.AdminManager().GetRoleList();
                    return View("RoleMaster", models);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult SaveNewRole(AdminRoleModel model)
        {
            try
            {
                if (model != null)
                {
                    LoginViewModel authenticatedUser = (LoginViewModel)(Session["user"]);
                    new Managers.AdminManager().InsertNewRole(model);
                }
                return RedirectToAction("RoleMaster");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public ActionResult ToggleActive(string State, string RoleID)
        {
            try
            {
                logger.Info("DeviceController ToggleActive Parameters: " + State + " " + RoleID);
                new Managers.AdminManager().UpdateRole(State, RoleID);
                //return RedirectToAction("RoleMaster");
                return Json(new { result = true });
            }
            catch (Exception ex)
            {
                logger.Error("Error in DeviceController ToggleActive" + ex.Message);
                return Json(new { result = false });
            }
        }

        public ActionResult DeleteRole(string RoleID)
        {
            try
            {
                AdminRoleModel model = new AdminRoleModel();
                model.AdminRoles = new Managers.AdminManager().DeleteRole(RoleID);
                return RedirectToAction("RoleMaster");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult SecurableFeaturesMaster(string FeatureID, string FeatureNames, string FeatureDescription)
        {
            try
            {
                SecurableFeaturesModel models = new SecurableFeaturesModel();
                models.SelectedOptionType = new Managers.SecurableFeatureManager().GetOptionType();
                models.SelectedToogleList = new Managers.SecurableFeatureManager().GetToggleList();
                if (!string.IsNullOrEmpty(FeatureID) || !string.IsNullOrEmpty(FeatureNames) || !string.IsNullOrEmpty(FeatureDescription))
                {
                    models.SecurableFeatures = new Managers.SecurableFeatureManager().GetSpecificSecurableFeatureList(FeatureID, FeatureNames, FeatureDescription);
                    return View("SecurableFeaturesMaster", models);
                }
                else
                {
                    models.SecurableFeatures = new Managers.SecurableFeatureManager().GetSecurableFeatureList();
                    return View("SecurableFeaturesMaster", models);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }


        public ActionResult SaveNewSecurableFeature(SecurableFeaturesModel model)
        {
            try
            {
                if (model != null)
                {
                    new Managers.SecurableFeatureManager().InsertNewSecurableFeature(model);
                }
                return RedirectToAction("SecurableFeaturesMaster");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public ActionResult ToggleOptionType(string State, string FeatureID)
        {
            try
            {
                logger.Info("AdminMastereController ToggleOptionType Parameters: " + State + " " + FeatureID);
                new Managers.SecurableFeatureManager().UpdateFeatureType(State, FeatureID);
                return RedirectToAction("SecurableFeaturesMaster");
            }
            catch (Exception ex)
            {
                logger.Error("Error in DeviceController ToggleActive" + ex.Message);
                throw ex;
            }
        }

        public ActionResult ToggleOptionValue(string State, string FeatureID)
        {
            try
            {
                logger.Info("AdminController ToggleOptionValue Parameters: " + State + " " + FeatureID);
                new Managers.SecurableFeatureManager().UpdateFeatureValue(State, FeatureID);
                return RedirectToAction("SecurableFeaturesMaster");
            }
            catch (Exception ex)
            {
                logger.Error("Error in DeviceController ToggleActive" + ex.Message);
                throw ex;
            }
        }


        public ActionResult RoleFeaturesMaster(string RoleName, string FeatureName)
        {
            try
            {
                RoleFeaturesModel models = new RoleFeaturesModel();
                models.SecurableFeatureList = new Managers.RoleFeatureManager().GetFeatureSelectableList();
                models.RoleUserList = new Managers.RoleFeatureManager().GetRoleSelectableList();
                if (!string.IsNullOrEmpty(RoleName) || !string.IsNullOrEmpty(FeatureName))
                {
                    models.RoleFeatures = new Managers.RoleFeatureManager().GetSpecificRoleFeatureList(RoleName, FeatureName);
                    return View("RoleFeaturesMaster", models);
                }
                else
                {
                    models.RoleFeatures = new Managers.RoleFeatureManager().GetRoleFeatureList();
                    return View("RoleFeaturesMaster", models);
                }
            }
            catch (Exception)
            {

                throw;
            }
        }

        public ActionResult SaveNewRoleFeature(RoleFeaturesModel model)
        {
            try
            {
                if (model != null)
                {
                    new Managers.RoleFeatureManager().InsertNewRoleFeature(model);
                }
                return RedirectToAction("RoleFeaturesMaster");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult ToggleActiveRoleFeature(string State, string RoleID, string FeatureID)
        {
            try
            {
                logger.Info("AdminController ToggleActiveRoleFeature Parameters: " + State + " " + RoleID + " " + FeatureID);
                new Managers.RoleFeatureManager().UpdateRoleFeature(State, RoleID, FeatureID);
                //return RedirectToAction("RoleFeaturesMaster");
                return Json(new { result = true });
            }
            catch (Exception ex)
            {
                logger.Error("Error in AdminController ToggleActive" + ex.Message);
                return Json(new { result = false });
            }
        }

        public JsonResult GetOptionTypeAndSettingValues(int featureID)
        {
            try
            {
                logger.Info("AdminController GetOptionTypeAndSettingValues Parameters: " + featureID);
                DataSet ds = new RoleFeatureManager().GetOptionType(featureID);
                return Json(new { optionType = Convert.ToString(ds.Tables[0].Rows[0]["OptionType"]), optionValue = Convert.ToString(ds.Tables[0].Rows[0]["OptionValue"]), defaultValue = Convert.ToString(ds.Tables[0].Rows[0]["DefaultValue"]) });
            }
            catch (Exception ex)
            {
                logger.Error("Error in AdminController ToggleActive" + ex.Message);
                return null;
            }
        }

        public JsonResult SaveRoleFeature(int roleId, int featureId, string settingValue)
        {
            try
            {
                char[] trimChar = { '|' };
                settingValue = settingValue.TrimStart(trimChar);
                logger.Info("AdminController SaveRoleFeature Parameters: " + roleId + " " + featureId + " " + settingValue);
                new Managers.RoleFeatureManager().SaveRoleFeature(roleId, featureId, settingValue);
                return Json(new { success = 1 });
            }
            catch (Exception ex)
            {
                if (ex.Message.Contains("Violation of PRIMARY KEY constraint 'pk_RoleFeatures'"))
                {
                    return Json(new { success = 2 });
                }

                logger.Error("Error in AdminController SaveRoleFeature" + ex.Message);
                return Json(new { success = 0 });
            }
        }
        // Delete Role
        public JsonResult DeleteRoleFeature(int roleID, int featureID)
        {
            try

SLEAdminPortal/Views/AdminMaster/RoleMaster.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Role Master";
}
@model SLEAdminPortal.Models.AdminRoleModel

<div class="wrapper wrapper-content animated fadeInRight">
    <div id="tabwhite" class="row">
        <div class="col-lg-12">
            <div class="tabs-container">
                <div class="tab-content">
                    <div id="tab-1" class="tab-pane active">
                        <div class="panel-body">
                            <form role="form">
                                @using (Html.BeginForm())
                                {
                                    <div class="form-group col-lg-3"><label>Role ID</label> @Html.TextBox("RoleID", null, new { @class = "form-control", @placeholder = "Role ID", @onkeypress = "return isNumber(event)" })</div>
                                    <div class="form-group col-lg-3"><label>Role Name</label>@Html.TextBox("RoleNames", null, new { @class = "form-control", @placeholder = "Role Name" })</div>
                                    <div class="form-group col-lg-3"><label>Description</label>@Html.TextBox("RoleDescription", null, new { @class = "form-control", @placeholder = "Description" })</div>
                                    <div class="form-group col-lg-3">
                                        <label>&nbsp;</label> <br />
                                        <button id="Search_Role" type="submit" class="btn btn-primary">
                                            Search
                                        </button>
                                    </div>
                                }
                                <div class="form-group col-lg-12"> <a data-toggle="modal" class="btn btn-primary" data-target="#myModal">Add  New Role</a> </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>
                                Total Roles : @if (Model != null)
                                { @Model.AdminRoles.Count }
                                else
                                {<span>0</span>}
                            </h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li>
                                        <a href="#">Config option 1</a>
                                    </li>
                                    <li>
                                        <a href="#">Config option 2</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Role ID</th>
                                        <th>Role Name</th>
                                        <th>Role Description</th>
                                        @*<th>Weightage</th>*@
                                        <th>Active</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        for (int i = 1; i <= @Model.AdminRoles.Count; i++)
                                        {
                                            <tr>
                                                <td>@i</td>
                                                <td>@Model.AdminRoles.ElementAt(i - 1).RoleID</td>
                                                <td>@Model.AdminRoles.ElementAt(i - 1).RoleName</td>
                                                <td>@Model.AdminRoles.ElementAt(i - 1).RoleDescription</td>
                                                @*<td>@Model.AdminRoles.ElementAt(i - 1).Weightage</td>*@
                                                <td id="lablebut" width="50">
                                                    @if (Model.AdminRoles.ElementAt(i - 1).Active == 1)
                                                    {
                                                        <button class="label label-primary" id="btnActive-@Model.AdminRoles.ElementAt(i - 1).RoleID" type="submit" onclick="ToggleActive(@Model.AdminRoles.ElementAt(i - 1).RoleID)">
                                                            Yes
                                                        </button>
                                                    }
                                                    else
                                                    {
                                                        <button class="label label-danger" type="submit" id="btnActive-@Model.AdminRoles.ElementAt(i - 1).RoleID" onclick="ToggleActive(@Model.AdminRoles.ElementAt(i - 1).RoleID)">
                                                            No
                                                        </button>
                                                    }
                                                </td>
                                                <td><div class="form-group col-lg-12"><a data-toggle="modal" class="btn btn-danger" onclick="Deletethisrecord('@Model.AdminRoles.ElementAt(i-1).RoleID')">Delete</a> </div></td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Add New Role</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("SaveNewRole", "AdminMaster", new { @class = "form-horizontal", role = "form" }))
                {
                    <div class="form-group">
                        <label for="recipient-name" class="control-label">Role Name</label>
                        @Html.TextBoxFor(model => model.RoleName, new { @class = "form-control", name = "RoleName", id = "RoleName" })
                        @Html.ValidationMessageFor(model => model.RoleName)
                    </div>

                    <div class="form-group">
                        <label for="message-text" class="control-label">Role Description</label>
                        @Html.TextBoxFor(model => model.RoleDescription, new { @class = "form-control", name = "RoleDescription", id = "RoleDescription" })
                    </div>
                    <br />
                    <div class="text-right">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@*<script>
        $(function () {
            $('.onoff').on('click', function () {
                var $this = $(this);
                var roleid = $this.attr('datatag');
                //ajax call
                //success
                $this.find('span')
            });
        });
    </script>*@

<script>
    function Deletethisrecord(findval) {
        if (confirm("Are you sure you want to delete this row?")) {
            var RoleID;

            $.ajax({
                url: '../AdminMaster/DeleteRole/?RoleID=' + findval + '',
                contentType: 'application/json; charset=utf-8',
                type: 'POST',
                cache: false,
                success: function (result) {
                    window.location.reload();
                },
                error: function (result) {
                }
            });
        }
    }

    function ToggleActive(RoleId) {
        var active = 'OFF';
        var act = $("#btnActive-" + RoleId).text().trim();
        if (act == "Yes")
            active = 'OFF';
        else
            active = 'ON';

        $.ajax({
            url: '@Url.Content("~")AdminMaster/ToggleActive',
            data: { RoleID: RoleId, State: active },
            dataType: 'json',
            type: 'POST',
            success: function (result) {
                if (result.result == true) {
                    if (act == "Yes") {
                        $("#btnActive-" + RoleId).removeClass("label-primary");
                        $("#btnActive-" + RoleId).addClass("label-danger");
                        $("#btnActive-" + RoleId).text("No");
                    }
                    else {
                        $("#btnActive-" + RoleId).removeClass("label-danger");
                        $("#btnActive-" + RoleId).addClass("label-primary");
                        $("#btnActive-" + RoleId).text("Yes");
                    }
                }
                else {
                    alert("Failed To Update Active Status");
                }
            },
            error: function (theError) {
                alert("Failed To Update Active Status");
            }
        });
    }
</script>

SLEAdminPortal/Views/AdminMaster/SecurableFeaturesMaster.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Securable Features";
}
@model SLEAdminPortal.Models.SecurableFeaturesModel

<div class="wrapper wrapper-content animated fadeInRight">
    <div id="tabwhite" class="row">
        <div class="col-lg-12">
            <div class="tabs-container">
                <div class="tab-content">
                    <div id="tab-1" class="tab-pane active">
                        <div class="panel-body">
                            <form role="form">
                                @using (Html.BeginForm())
                                {
                                    <div class="form-group col-lg-3"><label>Feature ID</label> @Html.TextBox("FeatureID", null, new { @class = "form-control", @placeholder = "Feature ID", @onkeypress = "return isNumber(event)" })</div>
                                    <div class="form-group col-lg-3"><label>Feature Name</label>@Html.TextBox("FeatureNames", null, new { @class = "form-control", @placeholder = "Feature Name" })</div>
                                    <div class="form-group col-lg-3"><label>Description</label>@Html.TextBox("FeatureDescription", null, new { @class = "form-control", @placeholder = "Description" })</div>
                                    <div class="form-group col-lg-3">
                                        <label>&nbsp;</label> <br />
                                        <button id="Search_SecFeature" type="submit" class="btn btn-primary">
                                            Search
                                        </button>
                                    </div>
                                }
                                <div class="form-group col-lg-12"> <a data-toggle="modal" class="btn btn-primary" data-target="#myModal">Add  New Feature</a> </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>
                                <b>
                                    Total Features : @if (Model != null)
                                    { @Model.SecurableFeatures.Count }
                                    else
                                    { <span>0</span> }
                                </b>
                            </h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li>
                                        <a href="#">Config option 1</a>
                                    </li>
                                    <li>
                                        <a href="#">Config option 2</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Feature ID</th>
                                        <th>Feature Name</th>
                                        <th>Feature Description</th>
                                        <th>Option Type</th>
                                        <th>Option Values</th>
                                        <th>Default Value</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        for (int i = 1; i <= @Model.SecurableFeatures.Count; i++)
                                        {
                                            <tr>
                                                <td>@i</td>
                                                <td>@Model.SecurableFeatures.ElementAt(i - 1).FeatureID</td>
                                                <td>@Model.SecurableFeatures.ElementAt(i - 1).FeatureName</td>
                                                <td>@Model.SecurableFeatures.ElementAt(i - 1).FeatureDescription</td>
                                                <td>@Model.SecurableFeatures.ElementAt(i - 1).OptionType</td>
                                                <td>@Model.SecurableFeatures.ElementAt(i - 1).OptionValue</td>
                                                <td>@Model.SecurableFeatures.ElementAt(i - 1).DefaultValue</td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Add New Feature</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("SaveNewSecurableFeature", "AdminMaster", new { @class = "form-horizontal", role = "form" }))
                {
                    <div class="form-group">
                        <span style="color: #e25856; left: 20px; position: absolute;">*</span>
                        <label for="recipient-name" class="control-label">Feature Name</label>
                        @Html.TextBoxFor(model => model.FeatureName, new { @class = "form-control", name = "FeatureName", id = "FeatureName" })
                        @Html.ValidationMessageFor(model => model.FeatureName)
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="control-label"> Feature Description</label>
                        @Html.TextBoxFor(model => model.FeatureDescription, new { @class = "form-control", name = "FeatureDescription", id = "FeatureDescription" })
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="control-label"> Option Type</label>
                        @Html.DropDownListFor(m => Model.SelectedOption, Model.SelectedOptionType, "Select Option", new { @class = "form-control", id = "SelectOption" })
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="control-label">Option Value</label>&nbsp;<span class="control-label small">(Separate by '|')</span>
                        @Html.TextBoxFor(model => model.OptionValue, new { @class = "form-control", name = "OptionValue", id = "OptionValue", disabled = "disabled" })
                    </div>
                    <div class="form-group" id="divDefault">
                        <label for="message-text" class="control-label">Default Value</label>
                        @Html.DropDownListFor(m => Model.DefaultValue, Model.SelectedOptionType, "Select Option", new { @class = "form-control", id = "ddlDefValue" })
                        @Html.DropDownListFor(m => Model.SelectedToggleValue, Model.SelectedToogleList, "No Select", new { @class = "form-control", id = "ddlToggle" })
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="control-label">From Portal Release</label>
                        @Html.TextBoxFor(model => model.FromPortalRelease, new { @class = "form-control", name = "FromPortalRelease", id = "FromPortalRelease" })
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="control-label">To Portal Release</label>
                        @Html.TextBoxFor(model => model.ToPortalRelease, new { @class = "form-control", name = "ToPortalRelease", id = "ToPortalRelease" })
                    </div>
                    <br />
                    <div class="text-right">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {

        $("#divDefault").hide();

        $("#SelectOption").change(function () {
            $("#divDefault").show();
            if ($("#SelectOption option:selected").text() == 'List') {
                $("#OptionValue").val('');
                $("#ddlDefValue").show();
                $("#ddlToggle").hide();
                $("#ddlDefValue").find('option').remove();
                $("#OptionValue").prop('disabled', false);
            }
            else {
                $("#OptionValue").val('');
                $("#ddlDefValue").hide();
                $("#ddlToggle").show();
                $("#ddlDefValue").find('option').remove();
                $("#OptionValue").prop('disabled', true);
            }
        });

        //$('#OptionValue').on('input', function () {
        //    var strOptionValue = $('#OptionValue').val();
        //    var arr = strOptionValue.split("|");
        //});

        $('#OptionValue').blur(function () {
            var strOptionValue = $('#OptionValue').val();
            var arr = strOptionValue.split("|");
            $("#ddlDefValue").find('option').remove();
            for (var i = 0; i < arr.length; i++) {
                //alert(arr[i]);
                if (arr[i] != '')
                    $("#ddlDefValue").append("<option value='" + arr[i] + "'>" + arr[i] + "</option>");
            }
        });
    });
</script>