SLEAdminPortal/Controllers/WindowsServiceController.cs
using sampleweb;
using SLEAdminPortal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceProcess;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace SLEAdminPortal.Controllers
{
    public class WindowsServiceController : Controller
    {
        public ActionResult Index()
        {
            try
            {

                var EnvList = new Managers.RouteSecurityManager().GetEnvDdl();
                ViewData["WSEnvironments"] = new SelectList(EnvList.OrderBy(x => x.EnvName), "EnvName", "EnvName");
               

                //IList<SLEAdminPortal.Models.Environment> EnvList = new List<SLEAdminPortal.Models.Environment>();
                //EnvList.Add(new SLEAdminPortal.Models.Environment() { EnvironmentName = "Prototype-DV" });
                //EnvList.Add(new SLEAdminPortal.Models.Environment() { EnvironmentName = "Prototype-PYD" });
                //EnvList.Add(new SLEAdminPortal.Models.Environment() { EnvironmentName = "Prototype-PYU" });
                //ViewData["WSEnvironments"] = new SelectList(EnvList, "EnvironmentName", "EnvironmentName");

                List<SelectListItem> DailyFrequentList = new List<SelectListItem>();
                DailyFrequentList.Add(new SelectListItem { Text = "Every 20 Mins", Value = "1", Selected = true });
                DailyFrequentList.Add(new SelectListItem { Text = "Every 1 Hour", Value = "2" });
                DailyFrequentList.Add(new SelectListItem { Text = "Every 3 Hours", Value = "3" });
                DailyFrequentList.Add(new SelectListItem { Text = "Every 12 Hours", Value = "4" });
                ViewData["Frequents"] = new SelectList(DailyFrequentList, "Text", "Text");


                List<SelectListItem> WeekDaysList = new List<SelectListItem>();
                WeekDaysList.Add(new SelectListItem { Text = "Sunday", Value = "1", Selected = true });
                WeekDaysList.Add(new SelectListItem { Text = "Monday", Value = "2" });
                WeekDaysList.Add(new SelectListItem { Text = "Tuesday", Value = "3" });
                WeekDaysList.Add(new SelectListItem { Text = "Wednesday", Value = "4" });
                WeekDaysList.Add(new SelectListItem { Text = "Thursday", Value = "5" });
                WeekDaysList.Add(new SelectListItem { Text = "Friday", Value = "6" });
                WeekDaysList.Add(new SelectListItem { Text = "Saturday", Value = "7" });
                ViewData["WeekDays"] = new SelectList(WeekDaysList, "Text", "Text");

                List<SelectListItem> RouteList = new List<SelectListItem>();
                RouteList.Add(new SelectListItem { Text = "Sales Order", Value = "1", Selected = true });
                RouteList.Add(new SelectListItem { Text = "Replenishment", Value = "2" });
                RouteList.Add(new SelectListItem { Text = "Receipts", Value = "3" });
                ViewData["Modules"] = new SelectList(RouteList, "Value", "Text");

                List<SelectListItem> RouteList1 = new List<SelectListItem>();
                RouteList1.Add(new SelectListItem { Text = "SalesOrder Status", Value = "1", Selected = true });
                RouteList1.Add(new SelectListItem { Text = "SalesOrder Process", Value = "2" });
                RouteList1.Add(new SelectListItem { Text = "Receipts Status", Value = "3" });
                RouteList1.Add(new SelectListItem { Text = "Receipts Process", Value = "4" });
                RouteList1.Add(new SelectListItem { Text = "Replenishment Status", Value = "5" });
                RouteList1.Add(new SelectListItem { Text = "Replenishment Process", Value = "6" });
                ViewData["SubModules"] = new SelectList(RouteList1, "Value", "Text");


                List<SelectListItem> DependencyList = new List<SelectListItem>();
                DependencyList.Add(new SelectListItem { Text = "Y", Value = "1", Selected = true });
                DependencyList.Add(new SelectListItem { Text = "N", Value = "2" });
                ViewData["Dependencys"] = new SelectList(DependencyList, "Value", "Text");


                //List<SelectListItem> EmailGroupList = new List<SelectListItem>();
                //EmailGroupList.Add(new SelectListItem { Text = "Replenishment Group", Value = "1", Selected = true });
                //EmailGroupList.Add(new SelectListItem { Text = "Sales Order Group", Value = "2" });
                //EmailGroupList.Add(new SelectListItem { Text = "Receipts Group", Value = "3" });

                //ViewData["EmailGroups"] = new SelectList(EmailGroupList, "Value", "Text");

                ServiceModel models = new ServiceModel();
                models.JobDetails = new Managers.ServiceManager().GetjobDetails();
                models.EffectiveFrom = DateTime.Now;
                models.EffectiveTo = DateTime.Now;
                var JobNameList = new Managers.ServiceManager().GetJobNameDdl();
                models.EmailConfigDetails = new Managers.ServiceManager().GetConfigDetails();
                var EmailGroup = new Managers.ServiceManager().GetEmailGroupDdl();
                string emailoption = "";
                foreach (var item in EmailGroup)
                {
                    emailoption = emailoption + item.ID + "-" + item.GroupEmailName + "_";
                }               
                ViewBag.emailoption = emailoption;
                ViewData["JobName"] = new SelectList(JobNameList.OrderBy(x => x.JobName), "JobID", "JobName");
                models.Services = new Managers.ServiceManager().GetServiceScheduleList();
                models.ImmediateServices = new Managers.ServiceManager().GetImmediateList();
                models.ServiceHistorys = new Managers.ServiceManager().GetServiceList();
                bool IsRunning = new Managers.ServiceManager().ServiceStatus();
                models.IsServiceRunning = IsRunning;
                return View("Index", models);
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }


        public ActionResult GetJobDetails(int JobID)
        {
            try
            {
                ServiceModel sc = new ServiceModel();
                sc.ModuleSequences = new Managers.ServiceManager().GetJobDetailsList(JobID);
                for (int i = 0; i < sc.ModuleSequences.Count();i++ )
                {
                    if(sc.ModuleSequences[i].Dependency=="True")
                    {
                        sc.ModuleSequences[i].Dependency = "Y";
                    }
                    else
                    {
                        sc.ModuleSequences[i].Dependency = "N";
                    }
                    if (sc.ModuleSequences[i].EmailNotification == "True")
                    {
                        sc.ModuleSequences[i].EmailNotification = "Y";
                    }
                    else
                    {
                        sc.ModuleSequences[i].EmailNotification = "N";
                    }
                }
                    return PartialView("_JobDetailsList", sc);
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }


        //public ActionResult StartService()
        //{

        //    int execute = new Managers.ServiceManager().ExecutionStatus();


        //    if (execute != 1)
        //    {
        //        ServiceController svcController = new ServiceController("DTService");

        //        if (svcController != null)
        //        {
        //            try
        //            {

        //                if (svcController.Status.ToString() == "Running")
        //                {
        //                    svcController.Stop();
        //                    svcController.Start();
        //                }
        //                else
        //                    svcController.Start();
        //            }
        //            catch (Exception ex)
        //            {
        //                //Todo: throw new application exeception
        //            }

        //        }
        //        // servicecontroller svccontroller = new servicecontroller("DTService"); ////rand.packetdownload is the service name
        //        //using (Impersonation imperson = new Impersonation("techunison", "marimuthu", "welcome@123"))
        //        //{
        //        //    ServiceController svccontroller = new ServiceController("DTService", "192.168.1.124");
        //        //    if (svccontroller.Status.ToString() == "running")
        //        //    {
        //        //        svccontroller.Stop();
        //        //        svccontroller.Start();
        //        //    }
        //        //    else
        //        //    {
        //        //        svccontroller.Start();
        //        //    }
        //        //}
        //    }
        //    else
        //    {
        //        int Waiting = new Managers.ServiceManager().UpdateWaiting();
        //    }


        //    return RedirectToAction("WindowsServiceIndex");
        //}

        public ActionResult UpdateScheduleList()
        {
            try
            {
                ServiceModel sc = new ServiceModel();
                sc.Services = new Managers.ServiceManager().GetServiceScheduleList();
                return PartialView("_ScheduleList", sc);
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }


        public ActionResult UpdateImmediateList()
        {
            try
            {
                ServiceModel sc = new ServiceModel();
                sc.ImmediateServices = new Managers.ServiceManager().GetImmediateList();
                return PartialView("_ImmediateList", sc);
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult UpdateEmailConfigDetails()
        {

SLEAdminPortal/Views/WindowsService/_EmailConfigList.cshtml
@model SLEAdminPortal.Models.ServiceModel
@using SLEAdminPortal.Models;



<div class="ibox-title">
    <h5>
        Total Configurations :@if (Model.EmailConfigDetails != null)
        { @Model.EmailConfigDetails.Count}
        else
        {<span>0</span>}
    </h5>
    <div class="ibox-tools">
        <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>
</div>
<div class="ibox-content">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Email Group Name</th>
                <th hidden>ID</th>
                <th style="text-align:center;">To Recipients</th>
                <th>Cc Recipients</th>
                @*<th>FQDN</th>*@
            </tr>
        </thead>
        <tbody>
            @if (Model.EmailConfigDetails != null)
            {
                if (@Model.EmailConfigDetails.Count == 0)
                {

                    <tr>
                        <td colspan="5" class="responseMsg">No Records to Display.!</td>
                    </tr>
                }
                for (int i = 1; i <= @Model.EmailConfigDetails.Count; i++)
                {
                    <tr>
                        <td>@i</td>
                        <td>@Model.EmailConfigDetails.ElementAt(i - 1).GroupEmailName</td>
                        <td hidden>@Model.EmailConfigDetails.ElementAt(i - 1).ID</td>
                        <td style="word-wrap:break-word;table-layout:fixed;word-break:break-all;text-align:center;">
                            @Model.EmailConfigDetails.ElementAt(i - 1).ToRecipients
                        </td>
                        <td style="word-wrap:break-word;table-layout:fixed">@Model.EmailConfigDetails.ElementAt(i - 1).CcRecipients</td>
                        <td id="lablebut">
                            <button type="submit" id="btnActive-@Model.EmailConfigDetails.ElementAt(i - 1).ID" onclick="EditEmailConfigDetails('@Model.EmailConfigDetails.ElementAt(i - 1).ID')" class="btn btn-primary">
                                Edit
                            </button>

                        </td>

                        <td>
                            <div class="form-group col-lg-12">
                                <a data-toggle="modal" class="btn btn-danger" onclick="DeleteEmailConfigDetails('@Model.EmailConfigDetails.ElementAt(i - 1).ID')" id="Delete-@Model.EmailConfigDetails.ElementAt(i - 1).ID">
                                    Delete
                                </a>
                            </div>
                        </td>

                    </tr>
                }

            }
            else
            {
                <tr>
                    <td colspan="5" class="responseMsg">No Records to Display.!</td>
                </tr>
            }
        </tbody>
    </table>
</div>

SLEAdminPortal/Views/WindowsService/_ImmediateDetailsList.cshtml
@model SLEAdminPortal.Models.ServiceModel
<table class="table order-item-detail-partialView-table" style=" width: 100%;">
    <thead>
        <tr>
            <th>Job Name</th>
            <th>Module Name</th>
            @*<th>Dependency</th>
            <th>Email Notification</th>*@
            @*<th>Dependency</th>
                <th>Email Notification</th>
                <th style="text-align:right; align-content:center; width:15%;">Email Group</th>*@

        </tr>
    </thead>
    <tbody>
        @if (@Model.ImmediateServices.Count == 0)
        {
            <tr>
                <td colspan="5" class="responseMsg">No Records to Display.!</td>
            </tr>
        }
        @for (int i = 1; i <= @Model.ImmediateServices.Count; i++)
        {
            <tr>
                <td>@Model.ImmediateServices[i - 1].JobName</td>
                <td>@Model.ImmediateServices[i - 1].ModuleName</td>
                @*<td>@Model.ImmediateServices[i - 1].Dependency</td>
                <td>@Model.ImmediateServices[i - 1].EmailNotification</td>*@
                @*<td>@Model.JobDetails.ElementAt(i - 1).ModuleSequences[j].Dependency</td>
                     <td>@Model.JobDetails.ElementAt(i - 1).ModuleSequences[j].EmailNotification</td>
                    <td>@Model.JobDetails.ElementAt(i-1).ModuleSequences[j].EmailAddress</td>*@
            </tr>
        }
    </tbody>
</table>

SLEAdminPortal/Views/WindowsService/_ImmediateList.cshtml
@model SLEAdminPortal.Models.ServiceModel
@using SLEAdminPortal.Models;



<div class="ibox-title">
    <h5>
        Total Schedule :@if (Model.ImmediateServices != null)
        { @Model.ImmediateServices.Count}
        else
        {<span>0</span>}

    </h5>
    <div class="ibox-tools">
        <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>
</div>
<div class="ibox-content">
    <table class="table">
        <thead>

            <tr>
                <th>#</th>
                <th>Job Name</th>
                <th hidden>ID</th>
                <th>Environment</th>
                <th>Created Date\Time</th>
                <th>Executed Date\Time</th>
                <th>Status</th>
                @*<th>FQDN</th>*@
            </tr>
        </thead>
        <tbody>
           @if (Model.ImmediateServices != null)
           { 
            if (@Model.ImmediateServices.Count == 0)
            {
                <tr>
                    <td colspan="5" class="responseMsg">No Records to Display.!</td>
                </tr>
            }
            for (int i = 1; i <= @Model.ImmediateServices.Count; i++)
            {
                <tr>
                    <td>@i</td>
                    <td>@Model.ImmediateServices.ElementAt(i - 1).JobName</td>
                    <td hidden>@Model.ImmediateServices.ElementAt(i - 1).JobID</td>
                    <td>@Model.ImmediateServices.ElementAt(i - 1).EnvironmentName</td>
                    <td>@Model.ImmediateServices.ElementAt(i - 1).CreatedDateTime</td>
                    <td>@Model.ImmediateServices.ElementAt(i - 1).UpdatedDateTime</td>
                    <td>@Model.ImmediateServices.ElementAt(i - 1).ScheduleStatus</td>
                </tr>
            }
            }
            else
           {
                 <tr>
                    <td colspan="5" class="responseMsg">No Records to Display.!</td>
                </tr>
           }
        </tbody>
    </table>
</div>

SLEAdminPortal/Views/WindowsService/_JobDetailsList.cshtml
@model SLEAdminPortal.Models.ServiceModel
<table class="table order-item-detail-partialView-table" style=" width: 100%;">
    <thead>
        <tr>
            <th>Sequence No</th>
            <th>Module Name</th>
            <th>Dependency</th>
            <th>Email Notification</th>
            <th>Email Group</th>
            @*<th>Dependency</th>
            <th>Email Notification</th>
            <th style="text-align:right; align-content:center; width:15%;">Email Group</th>*@
            
        </tr>
    </thead>
    <tbody>
        @if (@Model.ModuleSequences.Count == 0)
        {
            <tr>
                <td colspan="5" class="responseMsg">No Records to Display.!</td>
            </tr>
        }
        @for (int i = 1; i <= @Model.ModuleSequences.Count; i++)
        {
            <tr>
                <td>@Model.ModuleSequences[i-1].SequenceNo</td>
                <td>@Model.ModuleSequences[i-1].ModuleName</td>
                <td>@Model.ModuleSequences[i-1].Dependency</td>
                <td>@Model.ModuleSequences[i-1].EmailNotification</td>
                <td>@Model.ModuleSequences[i - 1].EmailAddress</td>
                @*<td>@Model.JobDetails.ElementAt(i - 1).ModuleSequences[j].Dependency</td>
                <td>@Model.JobDetails.ElementAt(i - 1).ModuleSequences[j].EmailNotification</td>
               <td>@Model.JobDetails.ElementAt(i-1).ModuleSequences[j].EmailAddress</td>*@
            </tr>
        }
    </tbody>
</table>

SLEAdminPortal/Views/WindowsService/_ScheduleList.cshtml
@model SLEAdminPortal.Models.ServiceModel
@using SLEAdminPortal.Models;




<div class="ibox-title">
    <h5>
        Total Schedule :@if (Model.Services!= null)
                { @Model.Services.Count}
                else
                {<span>0</span>}
    </h5>
    <div class="ibox-tools">
        <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
        </a>

    </div>
</div>
<div class="ibox-content order-list-box-container">
    <div class="order-list-container col-md-12">
        @if (Model.Services!= null)
                {
                if (@Model.Services.Count == 0)
                {
        <tr>
            <td colspan="5" class="responseMsg">No Records to Display.!</td>
        </tr>
                }
                for (int i = 1; i <= @Model.Services.Count; i++)
                {
        <div class="order-item-container col-md-12">
            <div class="order-item-header col-md-2" style="width:23%;">
                <span class="orderIdHeader">
                    <span class="header" hidden>
                        <span class="order-id-value ScheduleJobID">@Model.Services.ElementAt(i - 1).ScheduleID</span>
                    </span>
                    <span class="header">
                        Job Name:
                        <span class="order-id-value">@Model.Services.ElementAt(i - 1).JobName</span>
                    </span>
                    <br />
                    <span class="header">
                        Environment Name:
                        <span class="order-id-value">@Model.Services.ElementAt(i - 1).EnvironmentName</span>
                    </span>
                </span>
            </div>
            <div class="order-item-desc col-md-2" style="width:15%;">
                <span class="order-id-value" style="font-weight:bold;"> Created Date\Time: @Model.Services.ElementAt(i - 1).CreatedDateTime</span>
            </div>


            <div class="order-item-desc col-md-2">
                @if (string.IsNullOrEmpty(@Model.Services.ElementAt(i - 1).ScheduleStatus))
                            {
                        <span class="order-id-value" style="font-weight:bold;"> Last Run Date\Time:<br /> </span>
                            }
                            else
                            {
                        <span class="order-id-value" style="font-weight:bold;"> Last Run Date\Time:<br />@Model.Services.ElementAt(i - 1).UpdatedDateTime </span>
                            }
            </div>
            <div class="order-item-desc col-md-2">
                <span class="order-id-value" style="font-weight:bold;"> Next Run Date\Time:<br />@Model.Services.ElementAt(i - 1).NextRunTime </span>
            </div>

            <div class="order-item-desc col-md-2">
                <span class="order-id-value" style="font-weight:bold;"> Schedule Status:@Model.Services.ElementAt(i - 1).ScheduleStatus </span>
            </div>
            <div class="order-item-desc col-md-1">
                <div><button class="btn btn-primary" onclick="EditRegularSchedule('@Model.Services.ElementAt(i - 1).ScheduleID')">Edit</button></div>
            </div>


            <div class="order-item-desc col-md-1" style=" padding:0px 0px; width:0.3333333%;">
                <i class="fa fa-angle-down btn-scheduledetail  schedule-detail-click font-bold" style="font-weight:bold; font-size:14px; color:#646464; margin-left:5px; margin-top:15px; cursor:pointer" data-target=@Model.Services.ElementAt(i - 1).ScheduleID></i>
            </div>
            <div id="accordion1" class="schedule-detail-container col-md-12" data-element=@Model.Services.ElementAt(i - 1).ScheduleID>
                <div class="schedule-detail-panel col-md-12">
                    <div class="schedule-detail-title" style="font-weight:bold;">List of Schedule Details</div>
                    <div class="schedule-detail-list col-md-12">

                    </div>
                </div>
            </div>
        </div>
                }
                }
        else
        {
        <tr>
            <td colspan="5" class="responseMsg">No Records to Display.!</td>
        </tr>
        }
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        var accordionDiv = $('.schedule-detail-container').hide();
        var data2 = [
           [gd(2012, 1, 1), 7], [gd(2012, 1, 2), 6], [gd(2012, 1, 3), 4], [gd(2012, 1, 4), 8],
           [gd(2012, 1, 5), 9], [gd(2012, 1, 6), 7], [gd(2012, 1, 7), 5], [gd(2012, 1, 8), 4],
           [gd(2012, 1, 9), 7], [gd(2012, 1, 10), 8], [gd(2012, 1, 11), 9], [gd(2012, 1, 12), 6],
           [gd(2012, 1, 13), 4], [gd(2012, 1, 14), 5], [gd(2012, 1, 15), 11], [gd(2012, 1, 16), 8],
           [gd(2012, 1, 17), 8], [gd(2012, 1, 18), 11], [gd(2012, 1, 19), 11], [gd(2012, 1, 20), 6],
           [gd(2012, 1, 21), 6], [gd(2012, 1, 22), 8], [gd(2012, 1, 23), 11], [gd(2012, 1, 24), 13],
           [gd(2012, 1, 25), 7], [gd(2012, 1, 26), 9], [gd(2012, 1, 27), 9], [gd(2012, 1, 28), 8],
           [gd(2012, 1, 29), 5], [gd(2012, 1, 30), 8], [gd(2012, 1, 31), 25]
        ];

        var data3 = [
            [gd(2012, 1, 1), 800], [gd(2012, 1, 2), 500], [gd(2012, 1, 3), 600], [gd(2012, 1, 4), 700],
            [gd(2012, 1, 5), 500], [gd(2012, 1, 6), 456], [gd(2012, 1, 7), 800], [gd(2012, 1, 8), 589],
            [gd(2012, 1, 9), 467], [gd(2012, 1, 10), 876], [gd(2012, 1, 11), 689], [gd(2012, 1, 12), 700],
            [gd(2012, 1, 13), 500], [gd(2012, 1, 14), 600], [gd(2012, 1, 15), 700], [gd(2012, 1, 16), 786],
            [gd(2012, 1, 17), 345], [gd(2012, 1, 18), 888], [gd(2012, 1, 19), 888], [gd(2012, 1, 20), 888],
            [gd(2012, 1, 21), 987], [gd(2012, 1, 22), 444], [gd(2012, 1, 23), 999], [gd(2012, 1, 24), 567],
            [gd(2012, 1, 25), 786], [gd(2012, 1, 26), 666], [gd(2012, 1, 27), 888], [gd(2012, 1, 28), 900],
            [gd(2012, 1, 29), 178], [gd(2012, 1, 30), 555], [gd(2012, 1, 31), 993]
        ];


        var dataset = [
            {
                label: "Number of orders",
                data: data3,
                color: "#1ab394",
                bars: {
                    show: true,
                    align: "center",
                    barWidth: 24 * 60 * 60 * 600,
                    lineWidth: 0
                }

            }, {
                label: "Payments",
                data: data2,
                yaxis: 2,
                color: "#464f88",
                lines: {
                    lineWidth: 1,
                    show: true,
                    fill: true,
                    fillColor: {
                        colors: [{
                            opacity: 0.2
                        }, {
                            opacity: 0.2
                        }]
                    }
                },
                splines: {
                    show: false,
                    tension: 0.6,
                    lineWidth: 1,
                    fill: 0.1
                },
            }
        ];


        var options = {
            xaxis: {
                mode: "time",
                tickSize: [3, "day"],
                tickLength: 0,
                axisLabel: "Date",
                axisLabelUseCanvas: true,
                axisLabelFontSizePixels: 12,
                axisLabelFontFamily: 'Arial',
                axisLabelPadding: 10,
                color: "#d5d5d5"
            },
            yaxes: [{
                position: "left",
                max: 1070,
                color: "#d5d5d5",
                axisLabelUseCanvas: true,
                axisLabelFontSizePixels: 12,
                axisLabelFontFamily: 'Arial',
                axisLabelPadding: 3
            }, {
                position: "right",
                clolor: "#d5d5d5",
                axisLabelUseCanvas: true,
                axisLabelFontSizePixels: 12,
                axisLabelFontFamily: ' Arial',
                axisLabelPadding: 67
            }
            ],
            legend: {
                noColumns: 1,
                labelBoxBorderColor: "#000000",
                position: "nw"
            },
            grid: {
                hoverable: false,
                borderWidth: 0
            }
        };

        function gd(year, month, day) {
            return new Date(year, month - 1, day).getTime();
        }

        var previousPoint = null, previousLabel = null;

        var mapData = {
            "US": 298,
            "SA": 200,
            "DE": 220,
            "FR": 540,
            "CN": 120,
            "AU": 760,
            "BR": 550,
            "IN": 200,
            "GB": 120,
        };





        //Schedule Detail
        $('.btn-scheduledetail').click(function (e) {
            debugger;
            var currentElem = e.currentTarget;
            var dataId = $(currentElem).attr('data-target');

            var currentSelectedBtn = $('[data-element ="' + dataId + '"]').prev().find('.schedule-detail-click');
            var previousSelectedElement = accordionDiv.not('[data-element ="' + dataId + '"]').prev().find('.schedule-detail-click');
            //   var accordionDiv = $("tr#accordion").hide();

            $.ajax({
                // method: 'POST', <-- remove this
                type: 'POST', // <-- add this
                url: "@Url.Action("GetScheduleDetails", "WindowsService")",
                data: { ScheduleID: dataId },
                success: function (data) {
                    //var debugging = false; // or true
                    //if (typeof console == "undefined") var console = { log: function () { } };
                    //else if (!debugging || typeof console.log == "undefined") console.log = function () { };
                    console.log("success");
                    //$('[data-element ="' + dataId + '"] .order-detail-panel').find('.order-detail-list').html(data);
                    //$('[data-element ="' + dataId + '"] .order-detail-panel').addClass('selected');
                    $('[data-element ="' + dataId + '"] .schedule-detail-panel').find('.schedule-detail-list').html(data);
                    $('[data-element ="' + dataId + '"] .schedule-detail-panel').addClass('selected');
                    console.log(data);
                    // $(".order-detail-container").show();
                },
                error: function (error) {
                    console.log('error');
                }
            });
            accordionDiv.not('[data-element ="' + dataId + '"]').prev().removeClass('active');
            $('[data-element ="' + dataId + '"]').prev().addClass('active');
            $('[data-element ="' + dataId + '"]').slideToggle("slow");            
            if ($(currentSelectedBtn).hasClass('fa-angle-down'))
                $(currentSelectedBtn).removeClass('fa-angle-down').addClass('fa-angle-up');
            else {
                $(currentSelectedBtn).removeClass('fa-angle-up').addClass('fa-angle-down');

            }
            if (previousSelectedElement.hasClass('fa-angle-up'))
                previousSelectedElement.removeClass('fa-angle-up').addClass('fa-angle-down');
            accordionDiv.not('[data-element ="' + dataId + '"]').slideUp("slow");

        });







        $('#world-map').vectorMap({
            map: 'world_mill_en',
            backgroundColor: "transparent",
            regionStyle: {
                initial: {
                    fill: '#e4e4e4',
                    "fill-opacity": 0.9,
                    stroke: 'none',
                    "stroke-width": 0,
                    "stroke-opacity": 0
                }
            },

            series: {
                regions: [{
                    values: mapData,
                    scale: ["#1ab394", "#22d6b1"],
                    normalizeFunction: 'polynomial'
                }]
            },
        });

    });
</script>